exercícios deep dia 13/02/2026

In [1]:
import numpy as np

# Crie um array unidimensional (vetor) com os números de 10 a 20.

a = np.arange(10, 21)
print('vetor de 10 a 20:', a)

# Crie uma matriz 3x3 preenchida com zeros. Em seguida, transforme o elemento do centro (linha 1, coluna 1) em 9.

b = np.zeros((3, 3))
print('\nmatriz 3x3 0:')
print(b)

b[1,1] = 9
print('\nmodificado:')
print(b)

# Gere um array com 5 números aleatórios entre 0 e 1.

c = np.random.rand(5)
print('\n5 nmrs aleatórios:', c)

vetor de 10 a 20: [10 11 12 13 14 15 16 17 18 19 20]

matriz 3x3 0:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

modificado:
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

5 nmrs aleatórios: [0.48781421 0.71265291 0.71013718 0.94279981 0.1468084 ]


exercicios deep dia 14/02/2026

In [26]:
# Crie um array com 4 valores igualmente espaçados entre 0 e 1.

d = np.linspace(0, 1, 4)
print('d:', d)

# Dado o array e = np.array([10, 23, 45, 7, 38, 41, 15, 62, 53]), selecione e imprima os elementos das posições 3 a 6 (inclusive).

e = np.array([10, 23, 45, 7, 38, 41, 15, 62, 53]) 
print('\n original array:', e)
print('slicing 3-6:', e[3:7])

# Crie uma matriz 5x5 com valores de 1 a 25. Em seguida, selecione a última coluna e a primeira linha.

f = np.arange(1,26).reshape(5,5)
print('\nmatrix:')
print(f)

f_lastcolumn = f[:, -1]
print('last column:', f_lastcolumn)

f_firstrow = f[0, :]
print('first row:', f_firstrow)

# Do mesmo array e acima, imprima todos os elementos a partir do índice 4.

print('\n4 em diante do e:')
print(e[4:])

d: [0.         0.33333333 0.66666667 1.        ]

 original array: [10 23 45  7 38 41 15 62 53]
slicing 3-6: [ 7 38 41 15]

matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
last column: [ 5 10 15 20 25]
first row: [1 2 3 4 5]

4 em diante do e:
[38 41 15 62 53]
